# Generated by Django 5.2.16 on 2026-07-20 06:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=240)),
                ('version', models.CharField(max_length=20)),
                ('code_hash', models.CharField(max_length=64)),
                ('parameters', models.JSONField(default=dict)),
                ('risk_symbols', models.JSONField(default=list)),
                ('defensive_weights', models.JSONField(default=dict)),
                ('active', models.BooleanField(default=True)),
                ('locked', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name', '-published_at'],
                'constraints': [models.UniqueConstraint(fields=('slug', 'version'), name='unique_strategy_version')],
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signal_date', models.DateField(db_index=True)),
                ('tradable_on', models.DateField(db_index=True)),
                ('target_weights', models.JSONField(default=dict)),
                ('rationale', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signals', to='market.datasetsnapshot')),
                ('strategy_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signals', to='strategies.strategyversion')),
            ],
            options={
                'ordering': ['-signal_date'],
                'constraints': [models.UniqueConstraint(fields=('strategy_version', 'signal_date'), name='unique_strategy_signal_date')],
            },
        ),
    ]
