# Generated by Django 5.2.16 on 2026-07-20 11:48

import django.db.models.functions.text
from django.db import migrations, models


def make_display_names_unique(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    used: set[str] = set()
    for user in User.objects.order_by("date_joined", "id"):
        base = (user.display_name or "用户").strip()[:24]
        candidate = base
        if candidate.casefold() in used:
            suffix = f"-{str(user.id)[:4]}"
            candidate = f"{base[: 24 - len(suffix)]}{suffix}"
        user.display_name = candidate
        user.save(update_fields=["display_name"])
        used.add(candidate.casefold())


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RunPython(make_display_names_unique, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('display_name'), name='unique_user_display_name_ci'),
        ),
    ]
