# Generated by Django 5.2.16 on 2026-07-20 06:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cutoff_date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('digest', models.CharField(max_length=64, unique=True)),
                ('provider', models.CharField(max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('symbol', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('exchange', models.CharField(choices=[('XSHG', '上海证券交易所'), ('XSHE', '深圳证券交易所')], max_length=4)),
                ('lot_size', models.PositiveIntegerField(default=100)),
                ('listed_on', models.DateField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='MarketDataBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='eastmoney-akshare', max_length=40)),
                ('status', models.CharField(choices=[('running', '运行中'), ('healthy', '正常'), ('degraded', '异常'), ('failed', '失败')], db_index=True, default='running', max_length=12)),
                ('expected_session', models.DateField(blank=True, null=True)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('triggered_by', models.CharField(default='scheduler', max_length=80)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketBar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trade_date', models.DateField(db_index=True)),
                ('adjustment', models.CharField(choices=[('raw', '不复权'), ('hfq', '后复权')], max_length=3)),
                ('open', models.DecimalField(decimal_places=6, max_digits=18)),
                ('high', models.DecimalField(decimal_places=6, max_digits=18)),
                ('low', models.DecimalField(decimal_places=6, max_digits=18)),
                ('close', models.DecimalField(decimal_places=6, max_digits=18)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=24)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bars', to='market.instrument')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bars', to='market.marketdatabatch')),
            ],
            options={
                'indexes': [models.Index(fields=['instrument', 'adjustment', 'trade_date', 'is_current'], name='market_mark_instrum_5bb32e_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('instrument', 'trade_date', 'adjustment'), name='one_current_market_bar')],
            },
        ),
        migrations.CreateModel(
            name='CorporateAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('cash_dividend', '现金分红'), ('split', '份额拆分')], max_length=20)),
                ('record_date', models.DateField(blank=True, null=True)),
                ('effective_date', models.DateField(db_index=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('value', models.DecimalField(decimal_places=8, max_digits=18)),
                ('source_detail', models.JSONField(blank=True, default=dict)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corporate_actions', to='market.instrument')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corporate_actions', to='market.marketdatabatch')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('instrument', 'kind', 'effective_date'), name='one_current_corporate_action')],
            },
        ),
    ]
