# Generated by Django 5.2.16 on 2026-07-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketdatabatch',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
