# Generated by Django 5.2.16 on 2026-07-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_marketdatabatch_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='advice_eligible',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='instrument',
            name='asset_class',
            field=models.CharField(choices=[('equity', '股票'), ('bond', '债券'), ('money', '货币'), ('gold', '黄金'), ('cross_border', '跨境'), ('commodity', '商品'), ('unknown', '未分类')], db_index=True, default='unknown', max_length=16),
        ),
        migrations.AddField(
            model_name='instrument',
            name='average_amount_20d',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=24),
        ),
        migrations.AddField(
            model_name='instrument',
            name='catalog_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='data_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='data_status',
            field=models.CharField(choices=[('ready', '正常'), ('stale', '陈旧'), ('missing', '缺失'), ('blocked', '暂停')], db_index=True, default='missing', max_length=10),
        ),
        migrations.AddField(
            model_name='instrument',
            name='last_bar_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='instrument',
            name='settlement_cycle',
            field=models.CharField(choices=[('t0', 'T+0'), ('t1', 'T+1')], default='t1', max_length=2),
        ),
        migrations.AddField(
            model_name='instrument',
            name='trade_eligible',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='marketbar',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=24),
        ),
        migrations.AlterField(
            model_name='marketdatabatch',
            name='provider',
            field=models.CharField(default='sina-akshare', max_length=40),
        ),
    ]
