# Generated by Django 5.2.16 on 2026-07-20 06:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
        ('strategies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('side', models.CharField(choices=[('buy', '买入'), ('sell', '卖出')], max_length=4)),
                ('shares', models.PositiveIntegerField()),
                ('eligible_on', models.DateField()),
                ('status', models.CharField(choices=[('filled', '已成交'), ('rejected', '已拒绝')], max_length=10)),
                ('rejection_reason', models.CharField(blank=True, max_length=80)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.instrument')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Fill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=6, max_digits=18)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=18)),
                ('filled_on', models.DateField(db_index=True)),
                ('estimated', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='fill', to='paper.order')),
            ],
        ),
        migrations.CreateModel(
            name='PaperAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generation', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('active', '运行中'), ('archived', '已归档')], db_index=True, default='active', max_length=10)),
                ('initial_capital', models.DecimalField(decimal_places=2, default=100000, max_digits=18)),
                ('cash', models.DecimalField(decimal_places=2, default=100000, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('strategy_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paper_accounts', to='strategies.strategyversion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paper_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='paper.paperaccount'),
        ),
        migrations.CreateModel(
            name='NavSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('cash', models.DecimalField(decimal_places=2, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nav_snapshots', to='paper.paperaccount')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('deposit', '初始入金'), ('buy', '买入'), ('sell', '卖出'), ('fee', '费用'), ('dividend', '现金分红'), ('split', '份额拆分')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('quantity', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('occurred_on', models.DateField(db_index=True)),
                ('event_key', models.CharField(max_length=180, unique=True)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instrument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='market.instrument')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='paper.paperaccount')),
            ],
            options={
                'ordering': ['-occurred_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HoldingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('positions', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holding_snapshots', to='paper.paperaccount')),
            ],
        ),
        migrations.CreateModel(
            name='PaperRebalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('eligible_on', models.DateField(db_index=True)),
                ('target_weights', models.JSONField(default=dict)),
                ('source', models.CharField(choices=[('signal', '月末信号'), ('activation', '账户激活')], max_length=20)),
                ('status', models.CharField(choices=[('pending', '待估算'), ('processed', '已处理'), ('failed', '失败')], db_index=True, default='pending', max_length=12)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rebalances', to='paper.paperaccount')),
                ('signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paper_rebalances', to='strategies.signal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='rebalance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='paper.paperrebalance'),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shares', models.PositiveIntegerField(default=0)),
                ('average_cost', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='paper.paperaccount')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.instrument')),
            ],
        ),
        migrations.AddConstraint(
            model_name='paperaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user', 'strategy_version'), name='one_active_paper_account_per_strategy'),
        ),
        migrations.AddConstraint(
            model_name='paperaccount',
            constraint=models.UniqueConstraint(fields=('user', 'strategy_version', 'generation'), name='unique_account_generation'),
        ),
        migrations.AddConstraint(
            model_name='navsnapshot',
            constraint=models.UniqueConstraint(fields=('account', 'date'), name='unique_account_nav_date'),
        ),
        migrations.AddConstraint(
            model_name='holdingsnapshot',
            constraint=models.UniqueConstraint(fields=('account', 'date'), name='unique_account_holding_date'),
        ),
        migrations.AddConstraint(
            model_name='paperrebalance',
            constraint=models.UniqueConstraint(condition=models.Q(('signal__isnull', False)), fields=('account', 'signal'), name='unique_account_signal_rebalance'),
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.UniqueConstraint(fields=('account', 'instrument'), name='unique_account_position'),
        ),
    ]
