# Generated by Django 5.2.16 on 2026-07-20 11:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_instrument_advice_eligible_instrument_asset_class_and_more'),
        ('paper', '0002_papercyclerun'),
        ('strategies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdviceSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_date', models.DateField(db_index=True)),
                ('expires_on', models.DateField()),
                ('status', models.CharField(choices=[('ready', '有效'), ('stale', '已过期')], default='ready', max_length=8)),
                ('risk_level', models.CharField(choices=[('conservative', '保守'), ('balanced', '均衡'), ('aggressive', '进取')], max_length=12)),
                ('target_weights', models.JSONField(default=dict)),
                ('recommendations', models.JSONField(default=list)),
                ('input_summary', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-session_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PositionLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('acquired_on', models.DateField(db_index=True)),
                ('available_on', models.DateField(db_index=True)),
                ('quantity', models.PositiveIntegerField()),
                ('remaining_shares', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=6, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['available_on', 'acquired_on', 'created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='paperaccount',
            name='one_active_paper_account_per_strategy',
        ),
        migrations.RemoveConstraint(
            model_name='paperaccount',
            name='unique_account_generation',
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='client_request_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='expires_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='origin',
            field=models.CharField(choices=[('user', '用户委托'), ('legacy', '历史自动调仓')], default='legacy', max_length=8),
        ),
        migrations.AddField(
            model_name='order',
            name='reserved_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='paperaccount',
            name='mode',
            field=models.CharField(choices=[('manual', '自主交易'), ('legacy_auto', '历史自动账户')], db_index=True, default='legacy_auto', max_length=12),
        ),
        migrations.AddField(
            model_name='paperaccount',
            name='risk_level',
            field=models.CharField(choices=[('conservative', '保守'), ('balanced', '均衡'), ('aggressive', '进取')], default='balanced', max_length=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='rebalance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='paper.paperrebalance'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '待成交'), ('filled', '已成交'), ('rejected', '已拒绝'), ('cancelled', '已撤销'), ('expired', '已过期')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='paperaccount',
            name='strategy_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paper_accounts', to='strategies.strategyversion'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('client_request_id__isnull', False)), fields=('account', 'client_request_id'), name='unique_account_client_order_request'),
        ),
        migrations.AddConstraint(
            model_name='paperaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('mode', 'legacy_auto'), ('status', 'active')), fields=('user', 'strategy_version'), name='one_active_paper_account_per_strategy'),
        ),
        migrations.AddConstraint(
            model_name='paperaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('mode', 'manual'), ('status', 'active')), fields=('user',), name='one_active_manual_account_per_user'),
        ),
        migrations.AddConstraint(
            model_name='paperaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('mode', 'legacy_auto')), fields=('user', 'strategy_version', 'generation'), name='unique_legacy_account_generation'),
        ),
        migrations.AddField(
            model_name='advicesnapshot',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advice_snapshots', to='paper.paperaccount'),
        ),
        migrations.AddField(
            model_name='advicesnapshot',
            name='signal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='advice_snapshots', to='strategies.signal'),
        ),
        migrations.AddField(
            model_name='advicesnapshot',
            name='strategy_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advice_snapshots', to='strategies.strategyversion'),
        ),
        migrations.AddField(
            model_name='positionlot',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='position_lots', to='paper.paperaccount'),
        ),
        migrations.AddField(
            model_name='positionlot',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='position_lots', to='market.instrument'),
        ),
        migrations.AddField(
            model_name='positionlot',
            name='source_fill',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='position_lot', to='paper.fill'),
        ),
        migrations.AddConstraint(
            model_name='advicesnapshot',
            constraint=models.UniqueConstraint(fields=('account', 'strategy_version', 'session_date'), name='unique_account_strategy_advice_date'),
        ),
        migrations.AddIndex(
            model_name='positionlot',
            index=models.Index(fields=['account', 'instrument', 'available_on'], name='paper_posit_account_21a1be_idx'),
        ),
    ]
